spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=TRUE
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  logging:
    level:
      root: info
      com.yh.mybatis.mapper: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"