# application.yml
spring:
  application:
    name: skrshop-earth-system
  profiles:
    active: dev
server:
  port: 8084
  servlet:
    context-path: /skrshop/earthsystem
mybatis-plus:
  mapper-locations:  classpath*:mapper/**/*.xml
