# application.yml
spring:
  application:
    name: earth-system
  profiles:
    active: dev
server:
  port: 8081
  servlet:
    context-path: /earth/system
mybatis:
  mapper-locations:  classpath*:mapper/**/*.xml
