# application.yml
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/skrshop-earth-system?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=TRUE
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  application:
    name: skrshop-earth-system
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #  指定namespace
        # namespace: 04a067aa-178c-4fee-bc97-df5a6a4a23ff
        #指定集群名称
        cluster-name: NJ
        #metadata:
        #ins: 2
        #iw: 2323
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8084
  servlet:
    context-path: /skrshop/earthsystem
mybatis-plus:
  mapper-locations:  classpath*:mapper/**/*.xml
#  configuration:
#    default-enum-type-handler: com.skrshop.skrshoptkmybatis.handler.EnumCodeTypeHandler
feign:
  client:
    config:
      #想要调用的服务名称 default为全局配置
      default:
        LoggerLevel: basic
  httpclient:
    #Feign使用apacheClient进行请求而不是UrlConnection
    enabled: true
    #feign的最大连接数
    max-connections: 300
    #feign单个路径的最大连接数
    max-connections-per-route: 50