# application.yml
spring:
  application:
    name: skrshop-gateway

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root

  profiles:
    active: dev
server:
  port: 8081
  servlet:
    context-path: /skrshop/gateway
