# application.yml
spring:
  application:
    name: skrshop-oauth-center
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root


  profiles:
    active: dev
server:
  port: 8083
  servlet:
    context-path: /skrshop/oauth
mybatis-plus:
  mapper-locations:  classpath*:mapper/**/*.xml


#权限中心配置
skrshop:
  authority:
    security:
      #登录的请求页面
      loginpage: "/index.html"
      #登录的类型
      loginTypeEnum: JSON
      #      loginTypeEnum: REDIRECT
      #验证码配置
      code:
        #图形验证码配置
        image:
          enable: true
          width: 160
          height: 40
          codeCount: 4
          lineCount: 0
        #          url: "/skrshop/oauth/test/*"
        sms:
          enable: true
          codeCount: 8
