# application.yml
spring:
  application:
    name: skrshop-oauth-center
  redis:
     database: 0
     host: 127.0.0.1
     port: 6379
     password: root


  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
server:
  port: 8083
  servlet:
    context-path: /skrshop/oauth
mybatis-plus:
  mapper-locations:  classpath*:mapper/**/*.xml


#权限中心配置
skrshop:
  authority:
    security:
      loginpage: "/index"
      loginTypeEnum: JSON
