# application.yml
spring:
  application:
    name: skrshop-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root

  profiles:
    active: dev
server:
  port: 8081

