# application.yml
spring:
  application:
    name: mall
  profiles:
    active: dev
server:
  port: 8082
  servlet:
    context-path: /skrshop/mall
mybatis-plus:
    mapper-locations:  classpath*:mapper/**/*.xml
