# application.yml
spring:
  application:
    name: mall
  profiles:
    active: dev
server:
  port: 8081
  servlet:
    context-path: /skrshop/mall
mybatis:
  mapper-locations:  classpath*:mapper/**/*.xml
